### ISSUE TITLE
Renaming of json files to work

### ISSUE THREAD

**Issue by paulgrimley** [microsoft/CloudAdoptionFramework#1]
I had some issues running the Import-Export-Blueprints.ps1 to import the blueprint, what I found was that the json files needed renaming from CAF.json to Blueprint.json (Case sensitive) and Governance.json to Blueprint.json and this managed to import the Blueprints.

**Comment by BryanSoltis** [comment]
This issue is being closed due to the tool being re-designed using modern technologies.
