### ISSUE TITLE
AZNamingTool - uniquestring as optional component

### ISSUE THREAD

**Issue by Jonatan-V** [microsoft/CloudAdoptionFramework#103]
Hi
It would be great if you could add uniquestring (like the function you have in arm and bicep) as optional component.
You already mention it multiple times in the docs, ie https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-string#uniquestring
That way the resources can have unique names between ie environments, regions, etc without having to add all those components. And since "everyone" relies on the same components in their naming strategies it doesnt take long before you end up with a conflict (like kv-myapp-eus-dev). Uniquestring would help solve both.

**Comment by BryanSoltis** [comment]
Hi @Jonatan-V ,

Just to clarify, are you requesting the ability to generate a unique to be used as a component value? If so, that is an interesting 
feature that we may be able to work in. 

- Bryan

**Comment by Jonatan-V** [comment]
Hi @BryanSoltis 
Im requesting that you add a uniquestring component to the list, just like the other components mentioned here https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming
If possible, the uniquestring component should be able to return the same string as the arm and bicep function does, like uniqueString(resourceGroup().id) in bicep. That would require read permission on the subscription or resource group in Azure, which in turn could also be used to check name availability to avoid conflicts (but now in getting ahead of myself :).

Regards Jonatan

**Comment by BryanSoltis** [comment]
Hi @Jonatan-V ,

I wanted to let you know we release "Free Form Text" components today in v2.7.0 that should allow this functionality.  Hope you like it!

https://github.com/BryanSoltis/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

- Bryan
