### ISSUE TITLE
AzNamingTool - Feature Request: Filter and examples of lower-level scope resources.

### ISSUE THREAD

**Issue by hmizael** [microsoft/CloudAdoptionFramework#104]
When using Jump To, both in Reference and in Configuration, let it be a filter displaying only the resources of the selected provider or even the only resource selecting and not a "Go To". This makes the display cleaner.

And in reference, that even resources that are lower-level scope, have examples of names displayed.

Thank you very much.

**Comment by BryanSoltis** [comment]
Hi @hmizael ,

Thank you for your suggestion. We have a big PR currently being reviewed that contains a new "filter" feature for the list of resource types.  We are hoping to have these new features released this week!

![Filter](https://user-images.githubusercontent.com/13591910/196772721-d969174e-f3dc-4ec8-a7a3-196150411458.png)

- Bryan
