### ISSUE TITLE
AzNamingTool - Exporting Global Configuration does not include admin config

### ISSUE THREAD

**Issue by ciprianglg** [microsoft/CloudAdoptionFramework#109]
I'm trying to do an export for global configuration from web interface and i've ticked the check box to include Admin Configuration. When i'm looking at the exported file, the settings for Admin are set to null:

![image](https://user-images.githubusercontent.com/48557485/198974367-e9e445d7-1910-41e3-ba25-9006ffe00411.png)

![image](https://user-images.githubusercontent.com/48557485/198974496-824daf8f-ce84-4817-b006-ea1c6ec02972.png)

I'm using the latest version 2.3.0.

**Comment by BryanSoltis** [comment]
Hi @ciprianglg,

Thank you for the feedback. I have found the issue and added this fix to the current PR waiting to be merged. 

- Bryan

**Comment by ciprianglg** [comment]
@BryanSoltis on the latest version this is solved. Thanks,
