### ISSUE TITLE
Azure DevOps demo template is missing

### ISSUE THREAD

**Issue by tamatsuxyz** [microsoft/CloudAdoptionFramework#11]
I tried to create Azure DevOps by acloud adoption plan template,
but it failed because template zip is missing.

template link (this is missing/404 not found)
https://raw.githubusercontent.com/aksh-h/PUL_YML/master/PHP.zip

source doc:
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/template

**Comment by ckittel** [comment]
I just ran the deploy of the Demo Generator and did not experience this issue.  The legacy "Community -> Community T1" template is no longer exposed to the UI.  Going to close this issue, but feel free to reopen if the problem continues for you.
