### ISSUE TITLE
No resource type for Microsoft.Network/privateEndpoints

### ISSUE THREAD

**Issue by dazinator** [microsoft/CloudAdoptionFramework#110]
wanted to generate a name for a private endpoint that I am creating with bicep.
Couldn't see the resource type anywhere: Microsoft.Network/privateEndpoints, wondering if I am missing something or could this be added in future?

**Comment by Zimmergren** [comment]
This looks like a conversation tied to the AzNamingTool. 

The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
Please continue discussions or file new tickets in the new repo if there are still any issues! Thanks.
