### ISSUE TITLE
Broken Link in CAF/migrate

### ISSUE THREAD

**Issue by mailman-2097** [microsoft/CloudAdoptionFramework#111]
https://github.com/microsoft/CloudAdoptionFramework/tree/master/migrate

For more information on this tool, see the accompanying whitepaper: https://aka.ms/smartpaper.

The smartpaper link is broken

**Comment by srikanthyvr** [comment]
https://github.com/microsoft/CloudAdoptionFramework/tree/master/strategy

All the links are broken, could you please fix or direct us to the right links or files? Thanks in Advance :)

**Comment by Zimmergren** [comment]
@mailman-2097 , thanks for reporting this - we've removed that outdated whitepaper, but the link was remaining. I've removed the link.

@srikanthyvr , thanks - from the link you posted, the files are accessible. You'll have to click them, and then click "**View raw**", which allows you to access the underlying file.
