### ISSUE TITLE
AzNamingTool - No resource type for CosmosDB and LAW and AppService

### ISSUE THREAD

**Issue by hannovdm** [microsoft/CloudAdoptionFramework#113]
**Missing resource types**

- Add resource type to define the name for CosmosDb name, account and container
- Add resource type for Log Analytics Workspace names
- Add resource type for AppServiceName and appServicePlanName

**Comment by ciprianglg** [comment]
@hannovdm 
App service:
{
    "id": 330,
    "resource": "Web/sites",
    "optional": "UnitDept",
    "exclude": "Org,Function",
    "property": "Web App",
    "ShortName": "app",
    "scope": "global",
    "lengthMin": "2",
    "lengthMax": "60",
    "validText": "Contains alphanumerics and hyphens.",
    "invalidText": "Can\u0027t start or end with hyphen.",
    "invalidCharacters": "",
    "invalidCharactersStart": "-",
    "invalidCharactersEnd": "-",
    "invalidCharactersConsecutive": "",
    "regx": "^[a-zA-Z0-9][a-zA-Z0-9-]{0,58}[a-zA-Z0-9]$",
    "staticValues": ""
  },
  
  AppServicePlan:
  {
    "id": 328,
    "resource": "Web/serverfarms",
    "optional": "UnitDept",
    "exclude": "Org,Function",
    "property": "",
    "ShortName": "plan",
    "scope": "resource group",
    "lengthMin": "1",
    "lengthMax": "40",
    "validText": "Alphanumerics and hyphens.",
    "invalidText": "",
    "invalidCharacters": "",
    "invalidCharactersStart": "",
    "invalidCharactersEnd": "",
    "invalidCharactersConsecutive": "",
    "regx": "^[a-zA-Z0-9-]{1,40}$",
    "staticValues": ""
  },
  
  LogAnalyticsWorkspace:
  {
    "id": 259,
    "resource": "OperationalInsights/workspaces",
    "optional": "UnitDept",
    "exclude": "Org,Function",
    "property": "",
    "ShortName": "log",
    "scope": "global",
    "lengthMin": "4",
    "lengthMax": "63",
    "validText": "Alphanumerics and hyphens. Start and end with alphanumeric.",
    "invalidText": "",
    "invalidCharacters": "",
    "invalidCharactersStart": "",
    "invalidCharactersEnd": "",
    "invalidCharactersConsecutive": "",
    "regx": "^[a-zA-Z0-9-]{4,63}$",
    "staticValues": ""
  },
  
  CosmosDB:
  {
    "id": 158,
    "resource": "DocumentDB/databaseAccounts/sqlDatabases",
    "optional": "",
    "exclude": "",
    "property": "",
    "ShortName": "cosmos",
    "scope": "",
    "lengthMin": "",
    "lengthMax": "",
    "validText": "",
    "invalidText": "",
    "invalidCharacters": "",
    "invalidCharactersStart": "",
    "invalidCharactersEnd": "",
    "invalidCharactersConsecutive": "",
    "regx": "",
    "staticValues": ""
  },
  
  You can find all in https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/repository/resourcetypes.json.
  On my side i have all this under latest version. Maybe you need to update your resource database in the application.

**Comment by hannovdm** [comment]
Thank you. Not mentioned earlier I miss resource types in your json for:

- Add resource type for DDos Plan
- Add resource type for Private DNS Resolver

**Comment by Zimmergren** [comment]
The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
Please use the new repo to file a ticket if this is still an issue.
