### ISSUE TITLE
AzNamingTool - Resource types for Virtual Desktop

### ISSUE THREAD

**Issue by florian-ried** [microsoft/CloudAdoptionFramework#118]
Unfortunately, I could not find any resource types for Azure Virtual Desktop. However, in some VDI projects this would be mandatory for the naming convention.
It would be great if these could be built in.

Virtual desktop host pool | Microsoft.DesktopVirtualization/hostPools | vdpool
Virtual desktop application group | Microsoft.DesktopVirtualization/applicationGroups | vdag
Virtual desktop workspace | Microsoft.DesktopVirtualization/workspaces | vdws
Virtual desktop scaling plan | Microsoft.DesktopVirtualization/scalingPlans | vdscaling

BR - Florian

**Comment by jamasten** [comment]
Hi @florian-ried.  Thanks for the feedback!  However, we are fully aware that Azure resources are missing in tool.  The tool uses the metadata on the [Azure Naming Rules and Restrictions webpage](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) to create the metadata and regular expression for each resource. Unfortunately, this webpage is missing many Azure resources.  It's on our backlog to fix both the webpage and the tool but it takes time, and this tool is a side project for all of us that work on it.  The tool is open source, and all the resource metadata is stored resourcetypes.json file if you want to contribute to the tool.

**Comment by florian-ried** [comment]
Hi @jamasten 
Great, thank you for the quick feedback. Of course I'm interested in contributing to the tool and will take a look at the resourcetypes.json. Is there a guide on how resources can be included in this json?

**Comment by Zimmergren** [comment]
The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
Please continue any discussions in the new repo. cc @florian-ried @jamasten
