### ISSUE TITLE
AzNamingTool - Reference tab example names are ignoring the current delimiter

### ISSUE THREAD

**Issue by rohancragg** [microsoft/CloudAdoptionFramework#119]
The example names on the Reference tab (which I actually find more useful than the Generate tool) are not honouring the currently configured delimiter (dash in my case).

**Comment by BryanSoltis** [comment]
Hi @rohancragg,

Thank you for the feedback! I found the issue in the Reference page that was removing the default delimiter. This change will be included in the next tool update.

- Bryan

**Comment by BryanSoltis** [comment]
This has been fixed in the following PR: https://github.com/microsoft/CloudAdoptionFramework/pull/124

- Bryan
