### ISSUE TITLE
AzNamingTool - Generate tool should remind people that resources with lower-level scope do not need a unique name

### ISSUE THREAD

**Issue by rohancragg** [microsoft/CloudAdoptionFramework#120]
The Generate tool ignores its own advice on 'child' resource types such as SQL DB (I suppose that you might still want to generate a unique name but it ought to warn you that it's not recommended to do so)

**Comment by BryanSoltis** [comment]
Hi @rohancragg,

Great idea!  I added a warning message to the Generate page if the user selects a lower-level scope type. This will be included in the next tool update. Keep the feedback coming!

![image](https://user-images.githubusercontent.com/13591910/206209480-68cd63f2-750b-48a5-9e43-be5798c98415.png)

- Bryan

**Comment by BryanSoltis** [comment]
Hi @rohancragg.

I wanted to let you know this change has been added to the tool! Check out the latest version for details!

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/VERSIONHISTORY.md

- Bryan
