### ISSUE TITLE
AzNamingTool - Generate multiple resource names

### ISSUE THREAD

**Issue by rohancragg** [microsoft/CloudAdoptionFramework#122]
A couple of ways that this could be done:

Add an 'add' button to the Generate tool to accumulate a list of names based on the selected component values but a different resource type (and remember a list of the previously generated names).

Compile of a list of resource types that you need names for first and then ask the tool to generate a name for all of them. I guess this would be a bit like the example names in the Reference tool but for a list of 'favourite' resource types only.

**Comment by rohancragg** [comment]
It would also be good if the reference page also allowed us to control the component values that it uses in the examples, but then the Generate tool and the Reference tool would start to become functionally identical. Each tool has elements of what I'm actually looking for :-)

**Comment by BryanSoltis** [comment]
Hi @rohancragg,

These features have been added in the last few tool updates. Please see the release notes here:

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

You can now:
- Generate multiple resource type names at once
- Configure the site to prevent duplicate names from being generated

Thank you!

-Bryan
