### ISSUE TITLE
AzNamingTool - incorrect metadata for resource type Microsoft.KeyVault

### ISSUE THREAD

**Issue by rohancragg** [microsoft/CloudAdoptionFramework#123]
Tool does not agree with documented naming restrictions here:
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftkeyvault

Tool says that length can be 1 - 127 characters

This should be 3-24 characters

**Comment by jamasten** [comment]
This issue has been fixed in the following PR: https://github.com/microsoft/CloudAdoptionFramework/pull/124

**Comment by Zimmergren** [comment]
The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
This issue was already addressed in a previous PR, but if there are other issues arising, please use the new repo to file a ticket.
