### ISSUE TITLE
Naming convention validation

### ISSUE THREAD

**Issue by furrm** [microsoft/CloudAdoptionFramework#126]
Hi, can you confirm whether naming convention validation is included as part of the tool, please?

**Comment by jamasten** [comment]
Hi @furrm, the tool contains validation for most of the resources included in the tool.  There are a few that are missing validation, which includes "subscription".  You can check which ones are missing validation by looking at the [resourceTypes.json](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/repository/resourcetypes.json) file and look for any resource types missing a "regx" value.  We plan to correct this in the near future.
