### ISSUE TITLE
Subscription naming convention

### ISSUE THREAD

**Issue by furrm** [microsoft/CloudAdoptionFramework#127]
Hi,  the company I work for use `connectivity`, `management`, and `identity` as a naming convention for their platform landing zone subscriptions.  

All application landing zone subscriptions use something like `fshare-devl`.

Using the tool, how can I use longhand in some cases and shorthand in others?

I used the ` Projects/Apps/Services` component configuration for the `connectivity` sub with a shorthand name 'con', but when I attempt to generate a subscription name it forces the use of the shorthand name.

Is there a way, when adding values, that you can specify a flag to use shorthand or longhand?

Many thanks

**Comment by jamasten** [comment]
Hi @furrm, the tool assumes for consistency and simplicity that short names will be used everywhere.  We will put the feature request in our backlog and prioritize it based on all feedback we receive.  Thanks for the feedback!
