### ISSUE TITLE
AzNamingTool - High CPU usage on idle

### ISSUE THREAD

**Issue by bartlannoeye** [microsoft/CloudAdoptionFramework#128]
I was setting up a new configuration before lunch (local Docker image), including importing an edited config file. Upon returning I noticed my laptop's fans were running significantly harder than usual. A quick check in the task manager showed high CPU usage, even with the tab not having focus. Fan speed returned to normal soon after closing the tab.

![image](https://user-images.githubusercontent.com/5115577/210558727-e0c9535b-020e-4280-b0de-115de465d7f3.png)

**Comment by BryanSoltis** [comment]
Hi @bartlannoeye,

Thank you for the feedback. The site is a Blazor Server application and there is constant communication between the client & server. I suspect this is the activity you are seeing, although, I have not seen constant 100% utilization as you have you. In my experience, the Docker image usually hovers around 20% CPU and 100-120MB of RAM. The site will cache data to help on performance but does increase the RAM usage. I do regularly see Docker Desktop consume 100% of my host CPU for the VM Memory, which possible also is contributing to the behavior. 

We will definitely keep an eye on this and continue to improve performance and resource utilization where possible. Thank you!

- Bryan
