### ISSUE TITLE
Links are wrong in file initial-decisions-checklist.docx

### ISSUE THREAD

**Issue by slapointe** [microsoft/CloudAdoptionFramework#13]
The CAF documentation point to a document in this repository: https://raw.githubusercontent.com/Microsoft/CloudAdoptionFramework/master/references/initial-decisions-checklist.docx

A lot of links found in the document are wrong, pointing to a release branch in review.docs.microsoft.com

Also, @BrianBlanchard there is a lot of review notes at page 2. Is it still relevant?

**Comment by ckittel** [comment]
Closing as it was resolved last year with the above PR.
