### ISSUE TITLE
Resource Type explicitely include component

### ISSUE THREAD

**Issue by grabery** [microsoft/CloudAdoptionFramework#131]
So far it's possible to create your own components and make them globally optional or not. You also can edit the resource type and put it specifically on optional or excluded on that resource. But what I am missing is an explicit include of a component, so I do not have to update every single resource, if it's very resource specific.

Example:
For network peering, I like to know by the name, from where to where it's connected. Therefore I define a name something like "peer-vnet1-to-vnet2". The tool does not handle it usefully for such scenarios. I'd like to....

1. Add a new component
2. mark the component as "exclude everywhere"
3. go to peering resource type and edit
4. specifically include the newly created component and exclude all the unneeded.

This way, I would not affect all the other resources and I would not have to edit all of them, which is of course a pain :-)
Maybe there is also an other way to achieve this, if so, please guide me ;-)

**Comment by jamasten** [comment]
Hi @grabery. Thank you for your feedback.  The team met today, and we reviewed your feedback. We are looking into the best way to implement this feature and hope to release it in the near future.  In the meantime, you can make mass changes to the "optional" and "exclude" properties on the [resourcetypes.json](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/repository/resourcetypes.json) file using the find and replace feature in VSCode / code editor.

**Comment by grabery** [comment]
That makes sense, thx. It would be more convenient for my clients, if they're able to do so in the GUI though. Looking forward to the feature and thank you for your fast reply :-)

**Comment by jamasten** [comment]
Hi @grabery, to close the loop, this feature will be included in a release next month.  Be sure to follow our twitter feed / the repo to see when that change is pushed.

**Comment by jamasten** [comment]
Hi @grabery, the Azure Naming Tool now includes the ability to globally exclude a component or make it optional.
