### ISSUE TITLE
AzNamingTool - New Feature Request - Check for duplicate names

### ISSUE THREAD

**Issue by tarunchy** [microsoft/CloudAdoptionFramework#132]
I see currently we can generate same names multiple times. I think one of key benefit of this tool will be to make sure if name is already generated or taken someone this tool give some warning or error saying this is already generated by someone in the past. I can work contributing this enhancement

**Comment by BryanSoltis** [comment]
Hello @tarunchy,

Thank you for your feedback. Currently, the tool does not contain this functionality. It is in our backlog and will be released in a future update. 

- Bryan

**Comment by tarunchy** [comment]
Thank you Brian. If I take a shot and make the change. Will you accept my PR? whats the process of contributing to this code base

**Comment by BryanSoltis** [comment]
To be honest, I already have the code implemented, but we are evaluating the validity of it. The following changes are currently in a "testing" phase within the tool. There are several files where, so it's a bit to list.

- New setting to enable/disable duplicate name generation (Models/SiteConfiguration.cs, Shared/AdminModal.razor)
- New functionality to check if setting is enabled, if name is duplicate (Pages/Generate.razor, /Services/RequestNameGernationService.cs)

![6513866f-6111-4a5b-99e4-69cf2089120e](https://user-images.githubusercontent.com/13591910/214147896-333da61e-10d8-480d-8385-337786b26e73.jpg)
 
 The process (currently in testing) is as follows:
 - User attempts to generate a name
 - Name is validated using existing functionality
 - Setting is checked to see if duplicates are allowed
 - If disabled (the default setting), the site will check if the name being generated already existing in the GeneratedNamesLog
 - If it exists, the site displays a message saying the name exists and they need to select different options
 
![f713afa7-1238-4bda-9aed-dc8e92728200](https://user-images.githubusercontent.com/13591910/214147862-086ca4a5-2260-4f3e-a140-5663564e7670.jpg)

NOTE: The above changes are not final and may be modfiied.
 
For on-going development, anyone can contribute to the site. The process would be:
- Clone the repo
- Make modifications
- Submit a PR
- Our dev team (myself) would review the PR
- If approved, the PR would be submitted to the CAF engineering team to review
- Once approved, the PR would be merged into the CAF repo master branch
 
 -Bryan

**Comment by tarunchy** [comment]
Thank you Brian. Can do Testing of this code you have? Is there a Branch you have this updated code?

**Comment by BryanSoltis** [comment]
Thank you for checking out the code. It's important to note that these features are un-released and still in development.  They may change/be modified before public release.

**Comment by tarunchy** [comment]
Sure Bryan. Thank you so much for prompt response. I have more idea that we can make this tool effective for FinOps and CMDB update. I work for large health insurance company, part time educator in prestigious academic institute for MS students and also founder of multicloudcoe.com dlyog.com and fhir.top. Is it possible we meet for 30 mins to 1 hour call and I can share ny idea and we can collaborate in opensource forum
