### ISSUE TITLE
AzNamingTool - New Feature Request - Add option to configure web hook

### ISSUE THREAD

**Issue by tarunchy** [microsoft/CloudAdoptionFramework#134]
Hello,

If we can add feature when we generate name of resource we can call web hook propagate name to an external system as well via api call or web hook, then it will greatly enhance value of this tool. We can send this to other systems like CMDB e.g. Service Now or FinOps tools

-Tarun

**Comment by BryanSoltis** [comment]
Hi Tarun,

Thank you for the suggestion. This is an interesting idea and we have added it to our backlog for further consideration.

-Bryan

**Comment by BryanSoltis** [comment]
Hi Tarun,

This has been added in the latest updated. Please see the release notes here:

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

Thank you!
-Bryan
