### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by LocDaiLeFromTwoMany** [microsoft/CloudAdoptionFramework#139]
I have deploy the app to Azure Web App using GitHub Action. I get this error in Configuration page. 
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/99407358/216316645-2ef7f9f3-04c2-4cac-926b-e950eadf9251.png">

**Comment by BryanSoltis** [comment]
Hello,
The Azure Naming Tool requires internet connectivity for some of the features (Resource Type/Location refreshes, version checks, etc.). The site will attempt to download a 1px file from the following URL: 

https://github.com/aznamingtool/AzureNamingTool/blob/main/connectiontest.png 

If it cannot access the URL, it will determine that the site is not connected to the internet and display the message you are seeing. You may have some networking configuration that is preventing your Azure App Service to access that URL.

The disabled features only apply to updates to the resource types (New Azure services added) and location (new Azure regions added), which do not occur very often. Additionally, the tool updates are publicized on Twitter/LinkedIn. If you cannot resolve the issue for any reason, it will not affect very much of the functionality.  

- Bryan

**Comment by msoukhomlinov** [comment]
I have the same issue using the same deployment type, there are no restrictions on internet access. 

Is there a way to debug this?

**Comment by BryanSoltis** [comment]
Thank you for the additional feedback. To elaborate on the functionality, there is a function in the **/helpers/ConfigurationHelper.cs**  file called **VerifyConnectivty**. In the function, the site will attempt the following:

- Attempt to ping github.com (ping is often disabled in networks)
- If that fails, attempt to download a 1px file from https://github.com/aznamingtool/AzureNamingTool/blob/main/connectiontest.png
- If that fails, the site determines that there is no connectivity
- Updated/Version check features are disabled

If an exception is occurring in the process, there should be a message listed in Admin Log. Please check the log and let me know if you see any errors listed there.

To help in the future, we will add the following in the next update:

- Add a message in the Admin Log for the connectivity check response (in addition to any exceptions logged)
- Add a setting to bypass the connectivity check. The site will assume the site has connectivity and enable all features. This may cause additional exceptions in the Admin Log if the site attempts to enable "online" features and there is no connectivity.

I have added these features to current development version and will include them in the next release in a few weeks. I will update this thread once the features are enabled.

- Bryan
