### ISSUE TITLE
AzNamingTool - Filter field to generate single resource type name

### ISSUE THREAD

**Issue by antoineozenne** [microsoft/CloudAdoptionFramework#144]
When choosing to generate multiple resource type names, we can filter by name/short name to search the resource types.
Is it possible to add the ability to filter by name/short name on the resource types when generating a single resource type name? Currently, it is necessary to select the resource type provider and then select the resource type, which is less practical than being able to filter directly on the name.

**Comment by BryanSoltis** [comment]
Hi Antoine,

Thank you for your suggestions! We have added this our backlog and will attempt to incorporate it in the next release.

-Bryan
