### ISSUE TITLE
Specified delimeter is not allowed for "Compute/virtualMachines - Windows (vm)"

### ISSUE THREAD

**Issue by robm82** [microsoft/CloudAdoptionFramework#151]
I have been setting up the naming tool, and I get a message saying that the specified delimiter is not allowed for this resource type and has been removed:

![image](https://user-images.githubusercontent.com/47445676/226583531-a1f9547b-1bf7-43ec-9202-f1a65275fc2b.png)

I am using the default dash delimiter which is a "-", which should be an acceptable delimiter according to the naming tool (or have I misunderstood the regex?):

![image](https://user-images.githubusercontent.com/47445676/226584517-13f0453a-ab9d-4bec-98dd-86a114bb5978.png)

**Comment by robm82** [comment]
Again on this point, is 15 characters really the hard limit for creating Windows Virtual Machines? In the Azure portal I can create a VM up to 64 characters in length? Is it limited to 15 characters due to the Windows NetBIOS name being limited to 15 characters, and if you create a Windows VM longer than 15 characters it will truncate the name?
![image](https://user-images.githubusercontent.com/47445676/228791163-2fb51987-6a7a-439d-9da3-7ec0e25c6ca9.png)

**Comment by psilantropy** [comment]
Just deployed and I have the same issue today.
It only happens with **Compute/virtualMachines - Windows** not Linux. These two resource types output the same character length and structure.

![image](https://github.com/microsoft/CloudAdoptionFramework/assets/79955883/c1d74531-f7d2-47fe-a5ce-4267e7e31eca)

![image](https://github.com/microsoft/CloudAdoptionFramework/assets/79955883/77388721-8ba8-4c85-9515-8b5a32f2059a)

**Comment by psilantropy** [comment]
I worked around this by making the location optional for Windows VM, and then making additional environments selectable.
E.g. Aprd Bprd, A and B representing locations shortened from AXX and BXX.

This means it can be used for single Windows VMs, but doesn't function properly when generating multiple resources.

**Comment by Zimmergren** [comment]
The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
Please continue discussions or file new tickets in the new repo if there are still any issues! Thanks.

cc @psilantropy , @robm82 
FYI @BryanSoltis
