### ISSUE TITLE
AzNamingTool - New feature request: Add componet of type free text similar with instances

### ISSUE THREAD

**Issue by ciprianglg** [microsoft/CloudAdoptionFramework#153]
It will be great if we can have a  component that is of type free text, similar with what instance is doing with free number field. Reason behind is that to be able to link a "child" resource to parent resource. In this way when you look in the portal you will know which resource is used in which context.
Example:
`vm1`-proj1-prod-we-001
nic-proj1-`vm1`-prod-we-001
nic-proj1-`vm1`-prod-we-002
disk-proj1-`vm1`-prod-we-001
disk-proj1-`vm2`-prod-we-001

At the moment if you want to make it in this you ca use the function component, but you need to have the fields  populated in advance.

**Comment by BryanSoltis** [comment]
Hi @ciprianglg,

I wanted to let you know we release "Free Form Text" components today in v2.7.0 that should allow this functionality.  Hope you like it!

https://github.com/BryanSoltis/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

- Bryan

**Comment by ciprianglg** [comment]
@BryanSoltis I will give it a try next days. Thanks for the effort for implementation 👍
