### ISSUE TITLE
AzureNamingTool: Globally optional in version 2.5.0 does not apply when generating multiple resource type names

### ISSUE THREAD

**Issue by erlendjd** [microsoft/CloudAdoptionFramework#154]
After migrating optional components to new globally optional type in version 2.5.0 we have run into an issue when generating multiple resource type names at once. The component is not optional when generating multiple resource type names, but is optional when generating single resource type name.

First image showing that the component is optional when generating single resource type name:
![image](https://user-images.githubusercontent.com/57952635/229784080-ab5e32cf-fa64-41c2-938f-0cef7d1039e3.png)
As you can see it is optional and we can click generate whitout selecting a value for the component.

Second image showing that the component is not optional when generating multiple resource type names:
![image](https://user-images.githubusercontent.com/57952635/229784507-5f1c1c79-5d0d-4c1a-a06b-87ae2115b8fb.png)
As you can see it is not optional and we cant click generate without selecting a value for the component.

Third image showing that we can click generate if a value is set in the component:
![image](https://user-images.githubusercontent.com/57952635/229784842-47afc6a8-41d0-4d82-8b69-5ba4273f4ddb.png)

Hope to see this fixed in next version.

**Comment by BryanSoltis** [comment]
Hi @erlendjd,

Thank you for your feedback. This is a current limitation of the tool due to the way it handles optional components. We have a backlog item to update this, and we will address it in a future. release.  

Thank you!

-Bryan

**Comment by erlendjd** [comment]
Great, thanks for the fast response!
