### ISSUE TITLE
When Running the Command docker build -t azurenamingtool . from Linux Server an Error Showed up like nu1301 unable to load the service index for source

### ISSUE THREAD

**Issue by INPRASHANDHI** [microsoft/CloudAdoptionFramework#162]
Hello @BryanSoltis/ Anyone who can Help.

We are trying to run the Docker Image in Linux Server and executing the Command docker build -t azurenamingtool . there is an error showed like  nu1301 unable to load the service index for source.

Like Below Image

![image](https://github.com/microsoft/CloudAdoptionFramework/assets/109569901/db081d06-5cfc-4f08-b11a-7a812c50f693)

Can you guide or help how we can solve this issue to move Forward.

Awaiting Reply....

**Comment by INPRASHANDHI** [comment]
Anyone can Advise on this..

**Comment by INPRASHANDHI** [comment]
Hello @BryanSoltis Thank you for the reply. I was able to fix the issue and it was the https proxy address issue that was not added.

**Comment by BryanSoltis** [comment]
Glad you got it working!

-Bryan

**Comment by dexteravelasco** [comment]
How did you fix it?

**Comment by binteezyy** [comment]
> Hello @BryanSoltis Thank you for the reply. I was able to fix the issue and it was the https proxy address issue that was not added.

What exactly was the fix?
