### ISSUE TITLE
How to Make AzureNamingTool to Listen HTTPS Port

### ISSUE THREAD

**Issue by INPRASHANDHI** [microsoft/CloudAdoptionFramework#163]
Hello @BryanSoltis/ Anyone can help.

I have build the AzureNamingtool Image and its working fine now. But when I try to access like https://<siteurl> its not working 

I want to know how we can make azurenamingtool to listen https port.

I have created a docker compose file and its working as it should be for http but for https its not working . and other nginx setup is working as it should be. 

Can Anyone can help on this ?

**Comment by BryanSoltis** [comment]
Hello @INPRASHANDHI,

You will need to update your Docker environment with a certificate and execute a different command to host the tool on HTTPS.

Here is a guide on how to host a Docker site on HTTPS:

https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-6.0

You will need to:
- Create a certificate in your local Docker environment (or import an existing certificate)
- Run the tool as a container, specifying the certificate/ports for HTTP

Here is an example command I used to host the site on HTTPS:

docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="<YOUR CERTIFICATE PASSWORD>" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v %USERPROFILE%\.aspnet\https:/https/ azurenamingtool:latest azurenamingtool:latest

<img width="717" alt="image" src="https://github.com/microsoft/CloudAdoptionFramework/assets/13591910/6b9a73e3-a8df-40c5-9cd9-8743ce839e5a">

Hope this helps!

-Bryan

**Comment by INPRASHANDHI** [comment]
Hi @BryanSoltis I tried with the guide and I am using the docker compose for https and when I am following that I am receiving some warning and so its not working.

The message I receive is :

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[62]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {6f4628dc-f2fc-45a4-ae28-9a56a74453fe} with creation date 2023-05-24 15:23:47Z, activation date 2023-05-24 15:23:47Z, and expiration date 2023-08-22 15:23:47Z.

**Comment by INPRASHANDHI** [comment]
This is the docker compose file I am using:

version: "3"

services:
  aznamingtool:
    image: azurenamingtool:latest
    expose:
      - 8081
#      - 7070
#    ports:
#      - "8081:8081"
    environment:
      - VIRTUAL_HOST=sandbox.azurenamingtool.company.com
      - VIRTUAL_PORT=8081
#      - VIRTUAL_PORT=7070
      - DHPARAM_GENERATION=false
      - ASPNETCORE_URLS=http://+:8081
#      - ASPNETCORE_URLS=https://+:7070
    restart: always
    volumes:
      - ./azurenamingtoolvol:/app/settings

**Comment by INPRASHANDHI** [comment]
Am I missing here ?,,,

**Comment by BryanSoltis** [comment]
Glad you got it running! Definitely let us know if you run into any more issues.

- Bryan

**Comment by INPRASHANDHI** [comment]
Yes Sure @BryanSoltis , One Quick Question I have when we can expect AzureNamingTool Offcial Image in Docker Hub. Any timeline you guys have in your roadmap. Thank You.

**Comment by INPRASHANDHI** [comment]
Can you also share some docs to learn about different features and other stuffs related to AzureNamingTool

**Comment by BryanSoltis** [comment]
We are still in the process of getting the image part of mcr.microsoft.com. It's a long and complicated process that requests several actions by different teams. We will make an announcement once the process is complete. 

For documentation the site contains information on each page, via the Documentation link in the top right. Additionally, the GitHub repo contains videos, tutorials, and links to blog posts about the tool. 

[Overview](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool) | [Installation](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/INSTALLATION.md) | [Updating](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/UPDATING.md) | [Using the API](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/USINGTHEAPI.md) | [Release Notes](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md) | [Version History](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/VERSIONHISTORY.md) | [FAQ](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/FAQ.md) | [Contributors](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/CONTRIBUTORS.md)
