### ISSUE TITLE
Backing up all configuration and data from AzureNamingTool

### ISSUE THREAD

**Issue by INPRASHANDHI** [microsoft/CloudAdoptionFramework#167]
Hello @BryanSoltis 

How we can backup all the configurations and naming datas that I have created in azurenamingtool.

I can able to see export the configuration and store it anywhere and import it.

Do we have anyother options ? As I am running it as Docker Image in Linux Server. Do we have any ideas how we can do that.

Thank You....

**Comment by BryanSoltis** [comment]
Hello @INPRASHANDHI,

The primary way to backup the configuration is to use the Configuration utilities to export the globalconfig.json data.

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/UPDATING.md#backup-settings

If you are running the tool in a Docker container, then you should have a volume that was created when you launched the site (https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/INSTALLATION.md#run-as-a-docker-image). The commands in that guide will create a volume and mount it for the tool container to leverage.

When a volume is used, all settings are saved on the mounted volume and persisted. If the tool itself is updated, it will check if the /settings folder exists on the volume and use those files if present. Technically, you could also download the files from that volume as a backup strategy, however, it is recommended to use the Configuration utility for this process.

- Bryan

**Comment by BryanSoltis** [comment]
Closed due to inactivity.
