### ISSUE TITLE
Inconsistent Bootstrap reference

### ISSUE THREAD

**Issue by Eonasdan** [microsoft/CloudAdoptionFramework#177]
`_Layout.cshtml` references a bootstrap css file that is at version 5.1 but also references a CDN that uses 4.5.3 javascript file.

**Comment by BryanSoltis** [comment]
Hi @Eonasdan,

Thank you for your feedback! We will update this to Bootstrap 5.3 in the next release.

-Bryan

**Comment by BryanSoltis** [comment]
Hi @Eonsandan,

I wanted to let you know this issue has been fixed in the latest release.

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

-Bryan
