### ISSUE TITLE
Validate resource names

### ISSUE THREAD

**Issue by carlo-quinonez** [microsoft/CloudAdoptionFramework#181]
It would be nice if the naming tool provided an API to confirm whether a provided resource name (eg. `api-sud-spa-prd-ac-1 `) was valid based on the provided resource type (eg `ApiManagement/service/apis`). 

With a simple API like that, I could use IaC static code analysis tools to validate resource names before deployment. For example, [chekov](https://www.checkov.io/) can use [custom policies written in Python](https://www.checkov.io/3.Custom%20Policies/Python%20Custom%20Policies.html). It would be simple to call the validation API to check all the resource names to ensure compliance.

Right now, it's useful, but there's no way to enforce usage. Even if Azure Policy had support for regexs, the naming pattens can vary by resource types (like storage accounts) so a creating policy would be extremely complicated, not to mention the maintenance.

**Comment by jamasten** [comment]
Hi @carlo-quinonez. Thank you for the feedback!  This capability will be included in our next release.
