### ISSUE TITLE
Is there a way of auto using the next instance number available

### ISSUE THREAD

**Issue by SteveSitekitcare** [microsoft/CloudAdoptionFramework#184]
Hi

Is there a way I can generate the next instance name using the API, but without providing a instance number. Instead can this tool use the next available number automatically. This would allow me to use it to generate entire environments automatically

**Comment by SteveSitekitcare** [comment]
> 

Thanks for the reply

Any ideas when?

Steve

**Comment by Zimmergren** [comment]
The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
Please continue discussions or file new tickets in the new repo if there are still any issues! Thanks.

cc @SteveSitekitcare 

FYI @BryanSoltis
