### ISSUE TITLE
naming & tagging convention template - Naming convention inconsistencies

### ISSUE THREAD

**Issue by paraenggu** [microsoft/CloudAdoptionFramework#187]
First of all thanks a lot for providing the [Naming & Tagging standard template](https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/naming-and-tagging-conventions-tracking-template.xlsx)!

While studying [the template](https://github.com/microsoft/CloudAdoptionFramework/raw/1dcd7c70b176338b1a3aecc0fe6d1099ea37d5d5/ready/naming-and-tagging-conventions-tracking-template.xlsx), I noticed the following naming inconsistencies:
1. In the "intro and components" sheet, virtual machines are prefixed with `vm-`, while in the "Naming convention" sheet the format and example is missing the dash (`vm<policy name or appname><###>` / `vmsharepoint001`)
    * Also the question arises whether the VM number (`<###>`) wasn't supposed to be separated by a dash as with most other assets.
3. In the "Naming convention" sheet under _Virtual Machines_ the format and the example for the entries of the  _Load Balancer_  and  _NIC_ do not match (dash)
    * `lb-<app name or role><Environment><###>` / `lb-sharepoint-dev-001`
    * `nic-<##>-<vmname>-<subscription><###>` / `nic-02-vmhadoop1-prod-001`

General question:
 In the "intro and components" sheet most resource name prefixes include a dash (`-`) as the last character, while some are lacking one (e.g. `stor`, `ssimp`, `dls`, `dla` and `pbiemb`). Do they use a different schema intentionally and if yes, is there a technical limitation or similar to it, which could be noted as a comment in the sheet? The same question goes for the `<Environment>` separation of those assets in the "Naming convention" sheet.
 
 Thanks!

**Comment by shurik-io** [comment]
> In the "intro and components" sheet most resource name prefixes include a dash (-) as the last character, while some are lacking one (e.g. stor, ssimp, dls, dla and pbiemb). Do they use a different schema intentionally and if yes, is there a technical limitation or similar to it, which could be noted as a comment in the sheet?

I assume this is because of the character limit (24 IIRC) for storage based services, which have a global scope, thus saving some chars by not using the dashes in the naming scheme.

In general it would be nice to get answer on this topic, as I saw these stuff as well and had to fix it manually.

**Comment by Zimmergren** [comment]
Thank you for reporting this, @paraenggu. 
The linked file is over 4 years old, and drifted out of sync with the source of truth (CAF docs) - I would recommend checking out the official docs:
- https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging

Are you relying on the Excel file, specifically, or would you rather be able to keep up to date with the official docs, which are updated and maintained regularly? If I can understand how the Excel file is being used, we might be able to justify looking at an update. The way we see it right now, we're more likely to discontinue the Excel file and only keep the docs.

cc @shurik-io

**Comment by Zimmergren** [comment]
Thank you for the added thoughts on this, @paraenggu . 
We're planning to retire the file, and we'll then also remove the references from the content - we'll get this done asap to avoid further confusion, and we'll rely on the docs as the source of truth. 

Thanks!
Tobias.
