### ISSUE TITLE
Error while updating filepath parameter [azure-virtual-machine-cost-estimator.pbix]

### ISSUE THREAD

**Issue by hectorcubillos** [microsoft/CloudAdoptionFramework#190]
After download: 
- azure-virtual-machine-cost-estimator.pbix
- on-premises-compute-unit-lists.xlsx

I'm getting following error:
AzureBlobs failed to get the response: 'The remote name could not be resolved: 'cloudpricing.blob.core.windows.net''

**Comment by hectorcubillos** [comment]
It seems to be this issue has relationship to this one >
https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/889

**Comment by Zimmergren** [comment]
Thank you, @hectorcubillos - we're making a note of this and will investigate.

**Comment by mrunalbrahmbhatt** [comment]
Any updates ?

**Comment by Kohart** [comment]
how can we improve

**Comment by Zimmergren** [comment]
We're retiring these assets as they're outdated. The CAF Strategy section contains a list of other tools you might want to use.
