### ISSUE TITLE
How to create an issue for the Cloud Adoption Framework documentation?

### ISSUE THREAD

**Issue by paraenggu** [microsoft/CloudAdoptionFramework#207]
Hi, 

I would like to create an issue related to the [Cloud Adoption Framework documentation](https://github.com/MicrosoftDocs/cloud-adoption-framework).

The README of this repository states that this should be done on the  [cloud-adoption-framework](https://github.com/MicrosoftDocs/cloud-adoption-framework) repository:
> If you're looking to contribute to or report an issue regarding the Cloud Adoption Framework documentation found on Microsoft Docs, please visit the [Cloud Adoption Framework documentation repository on GitHub](https://github.com/MicrosoftDocs/cloud-adoption-framework).

However, GitHub issues seems to be disabled on the documentation repository and only pull-requests are possible. I was also unable to find any guidance on how to raise an issue within the README of the `cloud-adoption-framework` repo. I apologise for opening an issue on this repository instead, but I hope that someone here knows the intended way of raising an issue for the documentation.

Thanks!

**Comment by paraenggu** [comment]
OK thanks, so there's no way to do it over GitHub or another publicly accessible tracker to check whether there's already an existing or similar one?

**Comment by ckittel** [comment]
That is correct. It's a policy change on learn.microsoft.com.  https://learn.microsoft.com/en-us/contribute/content/provide-feedback

**Comment by paraenggu** [comment]
Alright, thanks a lot for your prompt feedback.
