### ISSUE TITLE
Two CAF repos on GitHub is one too many which makes it unclear which is which

### ISSUE THREAD

**Issue by noopman** [microsoft/CloudAdoptionFramework#29]
There are two Cloud Adoption Frameworks on GitHub. The on under Microsoft/CAF and the one under MicrosoftDocs/CAF. In small print one refers to the other, but it is not clear enough. Additionally, if you Google with Bing for “github cloud adoption framework” you get the one you are least likely to want to find first, and the second one is the docs one. Ask me how I know that someone can make that mistake!

https://github.com/microsoft/CloudAdoptionFramework
https://github.com/MicrosoftDocs/cloud-adoption-framework

I propose you make very clear in block letters that this is the supporting act and that people are likely looking for the other one!

**Comment by ckittel** [comment]
Hey there @noopman, great suggestion.  I added a note to this repo pointing back to the other.
