### ISSUE TITLE
Cannot access blob storage in azure-virtual-machine-cost-estimator.pbix

### ISSUE THREAD

**Issue by leeprtc** [microsoft/CloudAdoptionFramework#43]
This Power BI report is using https://cloudpricing.blob.core.windows.net/azurespecs/APIData/ResourceSkus.json. However, this blob is not public. When you download this pbix file and open it, you will get the following error.

AzureBlobs failed to get contents from 'https://cloudpricing.blob.core.windows.net/azurespecs/APIData/ResourceSkus.json'. Status code: 409, description: 'Public access is not permitted on this storage account.'.

Please enable public access for ResourceSkus.json blob.

**Comment by v-fearam** [comment]
It was already solved https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/889

I will close the ticket, but feel free to open a new one if you still have concerns.

#please-close

**Comment by v-fearam** [comment]
#please-close

**Comment by leeprtc** [comment]
Closing as requested.

**Comment by hectorcubillos** [comment]
This is not working again
https://cloudpricing.blob.core.windows.net/azurespecs/APIData/ResourceSkus.json

File not found
