### ISSUE TITLE
Option to make the Org component required for all resources

### ISSUE THREAD

**Issue by sarahjaneclark** [microsoft/CloudAdoptionFramework#52]
By design the Org component is excluded for most resources and only optional for high level resources, but would it be possible to make the Org component required for all resources so that it becomes a prefix in the naming convention?

**Comment by jamasten** [comment]
@sarahjaneclark I assume you are referring to the Azure Naming Tool, correct?  If so, you can remove the Org component  from the "exclude" column in the resources.csv file before you run the tool.  If you've already run the tool, you can re-run it and it will pull in your changes to any of the files in the "data" folder.

**Comment by sarahjaneclark** [comment]
Yes it was for the Naming Tool and that worked, thankyou very much.
