### ISSUE TITLE
Is it possible to add an extra custom component to the Naming Tool? - i.e. Function

### ISSUE THREAD

**Issue by sarahjaneclark** [microsoft/CloudAdoptionFramework#53]
Would it be possible to create an additional component to the Azure Naming Tool for the purpose of adding the function of the resource? After a discussion with the team it was identified that an additional component would be necessary to identify the function of the named resource. 

After trying to alter one of the other components to try and fit this purpose, it was clear they were locked down to their purpose and therefore I was unable to create a different component.

**Comment by jamasten** [comment]
Also, we plan to add a free form component in version 3 but that won't be released anytime soon.

**Comment by sarahjaneclark** [comment]
Hi Jason, thanks for the quick response. There are a few resources we have identified that would benefit from having a function component:

Storage to identify specific use i.e. data factory / state files / data bricks / function app
NSGs for  server / subnet / AKS
Public IPs and related resource
Resource Group - a description / function for the workload contained within the RG

The ProjAppSvc component identifies the specific app but a function component would further help, especially if the resource was fairly common and enumeration wouldn't help in identifying its function. This list of resources have only come to light in discussions or when first using the naming convention, but then when actually in use, it becomes clear that the name is not specific enough. So there may well be a number of other resources that would benefit from the function component as well.

**Comment by sarahclarkparentpay** [comment]
Hi Jason, thanks this option works great for us. However, the extra characters for VMs now exceeds the allowed length. Although this is highlighted with the validation warnings, is it possible to add a tick box to allow the removal of the delimiter when the size is exceeded?

**Comment by jamasten** [comment]
Hi @sarahclarkparentpay, thanks for the additional feedback and I'm glad I could resolve the function component for you.  I can add a condition to the code to remove the delimiter if the name is too long.  However, if you don't mind, this issue is related to the "function" component.  Could you please close this issue and open a new one?  Thanks!
