### ISSUE TITLE
Resource not appearing in Generate TAB

### ISSUE THREAD

**Issue by jacquesjung-clarins** [microsoft/CloudAdoptionFramework#60]
Hello,

i'm looking to generate a route table name.
In the Reference Tab, i well see Microsoft.Network/routeTables
![image](https://user-images.githubusercontent.com/105425290/168044809-b752e592-3e24-4775-ac14-55c78566bcfc.png)

But when i go to Generate, i don't get it in the list :
![image](https://user-images.githubusercontent.com/105425290/168045397-9b562d5a-e533-45b5-a243-fd946c5d7db0.png)

**Comment by jamasten** [comment]
Hi @jacquesjung-clarins, this resource was mistakenly added to the tool without any metadata.  As you may have noticed the tool is missing quite a few Azure resources.  We are currently collecting all the metadata for every Azure resource.  Once that data has been collected and posted to the [Azure Naming Restrictions webpage](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules), we will update the tool that will fix this resource and others.

**Comment by jacquesjung-clarins** [comment]
Hi Jason, thanks a lot for your answer.
Can you update me when you'll update it ? 
Thanks again

**Comment by jamasten** [comment]
@jacquesjung-clarins, I'll update this issue once the PR has been submitted.
