### ISSUE TITLE
Issue with PBIX azure-virtual-machine-cost-estimator.pbix

### ISSUE THREAD

**Issue by adamswbrown** [microsoft/CloudAdoptionFramework#61]
The PBIX makes calls to the pricing api that currently do not function

![image](https://user-images.githubusercontent.com/29273106/172233313-435d5ed8-7151-4566-a9c6-8d09432176aa.png)

This is occurring for all the Pricing API calls within the PBIX.

Error: 
DataSource.Error: Web.Contents failed to get contents from 'https://prices.azure.com/api/retail/prices?currencyCode='GBP%E2%80%8B'&$filter=%0A(indexof(location,%20'%20')%20ne%20-1%20or%20location%20eq%20'Global'%20or%20location%20eq%20'')%20%0Aand%20indexof(serviceName,%20'Virtual%20Machines')%20ne%20-1%20%0Aand%20indexof(productName,%20'%20Series')%20ne%20-1%0Aand%20indexof(productName,%20'%20Dedicated')%20eq%20-1%0Aand%20priceType%20eq%20'Consumption'%20%0Aand%20indexof(skuName,%20'Spot')%20eq%20-1%20%0Aand%20indexof(meterName,'Expired')%20eq%20-1%20%0Aand%20indexof(meterName,'Low%20Priority')%20eq%20-1%20%0Aand%20indexof(meterName,%20'Promo')%20eq%20-1' (400): Bad Request
Details:
    DataSourceKind=Web
    DataSourcePath=https://prices.azure.com/api/retail/prices
    Url=https://prices.azure.com/api/retail/prices?currencyCode='GBP%E2%80%8B'&$filter=%0A(indexof(location,%20'%20')%20ne%20-1%20or%20location%20eq%20'Global'%20or%20location%20eq%20'')%20%0Aand%20indexof(serviceName,%20'Virtual%20Machines')%20ne%20-1%20%0Aand%20indexof(productName,%20'%20Series')%20ne%20-1%0Aand%20indexof(productName,%20'%20Dedicated')%20eq%20-1%0Aand%20priceType%20eq%20'Consumption'%20%0Aand%20indexof(skuName,%20'Spot')%20eq%20-1%20%0Aand%20indexof(meterName,'Expired')%20eq%20-1%20%0Aand%20indexof(meterName,'Low%20Priority')%20eq%20-1%20%0Aand%20indexof(meterName,%20'Promo')%20eq%20-1

Example failing URL: 

https://prices.azure.com/api/retail/prices?currencyCode='GBP%E2%80%8B'&$filter=%0A(indexof(location,%20'%20')%20ne%20-1%20or%20location%20eq%20'Global'%20or%20location%20eq%20'')%20%0Aand%20indexof(serviceName,%20'Virtual%20Machines')%20ne%20-1%20%0Aand%20indexof(productName,%20'%20Series')%20ne%20-1%0Aand%20indexof(productName,%20'%20Dedicated')%20eq%20-1%0Aand%20priceType%20eq%20'Consumption'%20%0Aand%20indexof(skuName,%20'Spot')%20eq%20-1%20%0Aand%20indexof(meterName,'Expired')%20eq%20-1%20%0Aand%20indexof(meterName,'Low%20Priority')%20eq%20-1%20%0Aand%20indexof(meterName,%20'Promo')%20eq%20-1

 it looks like based on the error, the ODATA call is wrong, all Pricing API calls fail with the same error

**Comment by Zimmergren** [comment]
We're retiring this legacy tool. The CAF Strategy section contains a list of applicable tools, but this one will be removed from the list due to being unmaintained and legacy.
