### ISSUE TITLE
Access to Az ResourceSkus VMs Fails on azure-virtual-machine-cost-estimator.pbix

### ISSUE THREAD

**Issue by adamswbrown** [microsoft/CloudAdoptionFramework#62]
The PBIX references data stored in https://cloudpricing.blob.core.windows.net/azurespecs/APIData/ResourceSkus.json, this json requires a storage key that is not provided, and the query fails

**Comment by Zimmergren** [comment]
We're retiring this legacy tool. The CAF Strategy section contains a list of applicable tools, but this one will be removed from the list due to being unmaintained and legacy.
