### ISSUE TITLE
Q about updates to ESLZ visio

### ISSUE THREAD

**Issue by larryclaman** [microsoft/CloudAdoptionFramework#69]
@jtracey93, I noticed that you updated the ESLZ sample architecture visio on June 15 & added a number of new tabs, but I couldn't find any related documentation or changelog describing the purpose of these additional examples.  
https://github.com/microsoft/CloudAdoptionFramework/commits/master/ready/enterprise-scale-architecture.vsdx

Could you provide any additional info or context? (the new examples look quite useful & I'm anxious to share with my customers, but was hoping to have some context.) Thanks!

**Comment by jtracey93** [comment]
Hey @larryclaman,

I did indeed as part of PR #63 👍

Originally it was to fix a typo in the ALZ/ESLZ diagrams, but I also added other diagrams that are used across the CAF & ESLZ repo to make them publicly available to everyone. For example, I included the diagrams from https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/enterprise-scale/testing-approach & also https://github.com/Azure/Enterprise-Scale/blob/main/docs/media/es-hubspoke-nw.png from https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/adventureworks

Hope that answers your question 👍

**Comment by larryclaman** [comment]
thanks Jack!
