### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by furrm** [microsoft/CloudAdoptionFramework#70]
Hi, I have just installed the Azure Naming Tool.  I am finding that when generating a subscription name from the vanilla install, I get "Input string was not in a correct format." error.  This has happened for the local installation and Azure installation having followed your installation guidelines.

Any help would be very much appreciated.

**Comment by BryanSoltis** [comment]
Hi furrm,

This fix was released in the latest PR. Please download the latest codebase and recreate your image (if running Docker). If you leave your volume in place, your settings should be retained. If there is any concern, please use the Backup Configuration feature under the Configuration Page / Global Configuration section to download your current configuration.

- Bryan
