### ISSUE TITLE
AzNamingTool Feature Request: Tags

### ISSUE THREAD

**Issue by jag-sandhu** [microsoft/CloudAdoptionFramework#73]
The AzNamingTool v2 is brilliant.  I would want this to be a go to point in a business to get azure resource naming conventions and also Tagging conventions/mandatory tags 

Is it possible to add a section for mandatory tags? We have tags enforced via Policy and it would be nice if we had a central tool, where resource names and tags can be referenced. 

Another feature which would be handy, but I appreciate it may be out of scope here is, AAD Security Group Naming convention, where users can reference how they should be naming AAD Groups as per business naming convention.

**Comment by BryanSoltis** [comment]
Hi @jag-sandhu

Thank you for the feedback! The Azure Naming Tool currently does not have any direct integration with your Azure Subscription. As such, it cannot dictate any tags to be created on a resource. We have considered adding this integration int he future and it is currently in our backlog and being evaluated. 

- BryanSoltis
