### ISSUE TITLE
Azure Naming Tool - Org Component Required

### ISSUE THREAD

**Issue by sarahjaneclark** [microsoft/CloudAdoptionFramework#75]
Hi, previously in version 1.0 of the naming tool, I opened an issue as I wanted to make the Org component compulsory for all resources. Now I am using version 2.0, how do I apply the same change? -

_you can remove the Org component from the "exclude" column in the resources.csv file before you run the tool. If you've already run the tool, you can re-run it and it will pull in your changes to any of the files in the "data" folder._

**Comment by BryanSoltis** [comment]
Hi @sarahjaneclark, V2 uses JSON files for all configurations. This is similar to how V1 used .CSV files, but a more usable format. In the **/settings/resourcetypes.json** file (if you already have the tool installed), you will see all the resource types and their respective details. Included in those details are "optional" and "exclude" properties. By default, nearly every resource type has "Org" listed in the "exclude" property, per the default settings.  To manually address your issue, you could edit that file to remove the "Org" value from the "optional" and "exclude" properties for the resource types. 

If you had a specific resource type you wanted to edit, you can do that on the Configuration page by selecting the "Edit" button for the desired resource type, then deselecting "Org" from the exclude and/or optional settings. I'm guessing you want to do this bulk, so editing the file manually may be faster.

We will evaluate adding a bulk, "require component for all resource types" feature to see if it makes sense. 

Thank you for the feedback!

**Comment by sarahjaneclark** [comment]
This works great, thank you for responding so quickly.
