### ISSUE TITLE
Azure Naming Tool - Custom ResourceComponents

### ISSUE THREAD

**Issue by tobvil** [microsoft/CloudAdoptionFramework#76]
The projects/apps/services resource component requires all projects to be created beforehand, and doesn't allow user to input their own project name. This is also a risk because if we add all project names, we risk users seeing confidential project names.

Would be nice if we could create additional resource components, that accepts input during naming generation.

**Comment by BryanSoltis** [comment]
Hi tobvil,

Thank you for your feedback! You make an excellent point on how companies will actually use the tool and project names needing to be modified over time. We actually have this in our backlog of features to add to the site and will hopefully be releasing this capability in the next few months.

- Bryan

**Comment by BryanSoltis** [comment]
Hi @tobvil,

I wanted to let you know we released V2.2.0 of the Azure Naming Tool that includes support for Custom Components. Please check it out and let us know if you have any questions!

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/VERSIONHISTORY.md

Bryan

**Comment by tobvil** [comment]
Is it possible to create a Custom Component with an input field?
The new Custom Component still requires you to create all the possible input's before using the name generator.

**Comment by BryanSoltis** [comment]
Not at this time. It's a feature we are considering, but it has implications on name length/symbols/etc. when it's a free form text field. We will continue to research the concept and implement it at a later date, if it's possible.

**Comment by BryanSoltis** [comment]
Hi @tobvil,

Free Form Text components have been added to the tool in the latest release. Please see the release notes here:

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

Thank you!

-Bryan
