### ISSUE TITLE
Feature Request: Resource Types for Container Apps

### ISSUE THREAD

**Issue by Naboo2604** [microsoft/CloudAdoptionFramework#81]
A great tool many thanks!

please add resource types for::

Container Apps
Container Apps Environments
Container Apps Environments Storage Settings

**Comment by BryanSoltis** [comment]
Hi Naboo264.

Thank you for your suggestion! We are constantly updating the list of resource types as they are made publicly available. It's a bit of a manual process to combine all the details (regex, valid characters, etc.), so we try and get them done as soon as we can.

The good news is that the tool allows you to update the resource type directly from the Configuration Page. To update the resource types with the latest data: 

- Log in as the Admin
- Go to the Configuration Page
- Under Component Configuration, expand Resource Types
- Expand the Configuration section
- Select the **Refresh the Resource Types Configuration** option to update the configuration from the GitHub repo

This process will add any new resource typ4es to your local configuration. IT will not modify any of your current customizations.

Hope this helps!
- BryanSoltis

**Comment by Frikki** [comment]
Why can’t we add the resource types ourselves?

**Comment by Zimmergren** [comment]
The AzNamingTool repo moved: https://github.com/mspnp/AzureNamingTool
Please continue discussions or file new tickets in the new repo! Thanks.
