### ISSUE TITLE
Feature Request: Add / Rename Components

### ISSUE THREAD

**Issue by Parlax** [microsoft/CloudAdoptionFramework#85]
Currently it's only possible to remove or add preconfigured components. It would be a nice feature to be able to add custom components to this list or rename the existing components to align with our company policy.

**Comment by tkossa** [comment]
I agree, it could be an great addition.

I tried some stuff to achieve that but i was not able to make it work : 
1/ tried to change the name value of a component in the global config files (Not worked)
2/tried to use the API to change values (Not worked)
3/tried to modified json files into the /repository folder (not worked)

are there any "hardcoded" values somewhere ?

**Comment by BryanSoltis** [comment]
This feature is currently on our roadmap. The site currently relies on the component types to be a very specific name/structure and these values not able to be changed. The planned feature will allow you to add custom components and set their order along with the "standard" ones.

**Comment by BryanSoltis** [comment]
Big update currently being tested! Hoping to release next week....

![image](https://user-images.githubusercontent.com/13591910/187755705-47b08df6-770c-496f-a864-e660476daf7f.png)

-Bryan

**Comment by BryanSoltis** [comment]
Big update being tested!  Hoping to release next week....

![image](https://user-images.githubusercontent.com/13591910/187757220-9200af3c-186f-4e3f-9ea3-aa60bd0451be.png)

![image](https://user-images.githubusercontent.com/13591910/187757306-7a2899a9-52f4-42b4-8d79-e0e41ccdaef6.png)

- Bryan

**Comment by BryanSoltis** [comment]
Hi @Parlax & @tkossa,

I wanted to let you know we released V2.2.0 of the Azure Naming Tool that includes support for Custom Components. Please check it out and let us know if you have any questions!

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/VERSIONHISTORY.md

- Bryan
