### ISSUE TITLE
New CISO Workshop PowerPoint File

### ISSUE THREAD

**Issue by Xentraxx** [microsoft/CloudAdoptionFramework#88]
Hello Microsoft Team,

I'm working as a Cybersecurity Consultant and I do CISO Workshops with my customers to make them understand the security advantages of moving to the Cloud and help them with strategic guidance as well.

In the past I used the old Workshop as a Reference and I included some of the slides, because they are really informative.
I wonder why you only provide the new CISO Workshop in a PDF format.

It would be awesome if you could also upload a Powerpoint file, so we can include your guidance in our Workshop to help your customers to understand what the Strategy of Microsoft is and how your products can help them to become more secure.

As I understand it, the Workshop is published under the MIT License, but without the right of using any Microsoft Logos and Trademarks, but with the PDF we can't remove those.

**Comment by Zimmergren** [comment]
Currently, the CISO workshop materials are available here: https://learn.microsoft.com/en-us/security/adoption/the-ciso-workshop
