### ISSUE TITLE
AZNamingTool - publish to mcr.microsoft.com

### ISSUE THREAD

**Issue by Jonatan-V** [microsoft/CloudAdoptionFramework#92]
Hi 
I think the title says it all :)
It would be great if you could publish the Azure Naming Tool image to your public registry to ease the deployment for everybody.

Regards
Jonatan

**Comment by BryanSoltis** [comment]
Hi @Jonatan-V ,

That's a great suggestion! We are working with other Microsoft teams to get the image hosted in a public registry and hopefully will have that soon!

- Bryan

**Comment by hmizael** [comment]
For now I'm keeping my repository updated, feel free.

hmizael/azurenamingtool

**Comment by hmizael** [comment]
Updated to v2.3.2

**Comment by baf** [comment]
@BryanSoltis - any update on getting this published to a public registry?

**Comment by BryanSoltis** [comment]
Hello Brendan,

We have not made much progress this as of yet. It's quite a process to get a new public image included in the registry and we have been focusing on other items. It is still in our backlog and we will keep trying in the future.

-Bryan

**Comment by baf** [comment]
Hi, Bryan, sorry to hear that it's such an onerous process to get that done. Appreciate your efforts!

**Comment by BryanSoltis** [comment]
This issue has been added to our backlog and will be considered for a future update.
