### ISSUE TITLE
AzNamingTool - missing elements in resourcetypes.json

### ISSUE THREAD

**Issue by andreabisiach** [microsoft/CloudAdoptionFramework#93]
Hi,

I am evaluating your great tool and I have noticed discrepancies between https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/repository/resourcetypes.json and https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

In some cases, the entry is missing in resourcetypes.json (i.e. appi- , plan-) in other it's different (i.e. app- vs wapp- for Web app)
Will your tool be the official list from Microsoft?

/Andrea

**Comment by jamasten** [comment]
Hi @andreabisiach,

The Azure Naming Tool is a community tool that was created and developed by Microsoft employees. We have the support of the CAF team but the tool is not officially part of the CAF program yet. We're working on it. However the tool is listed on the [CAF Tools & Templates webpage](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/resources/tools-templates#ready). The CAF documentation is managed by a separate team. While we have collaborated on the content to bring our documentation, landing zones, and tooling in alignment, some changes may have been added by the public or internal contributors that do not follow our workflow. We are actively working this issue to fix the alignment but to also address the missing Azure resources. The resources listed in the tool are based on [another Docs page](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) which is missing content. While we hope to have the fixes in place in the near future, please understand this is a manual effort and takes time.

Best,
Jason Masten

**Comment by andreabisiach** [comment]
Thank you @jamasten,

I will close this issue

Regards
Andrea
