### ISSUE TITLE
Feature Request: Custom fields for end user

### ISSUE THREAD

**Issue by JClarke90** [microsoft/CloudAdoptionFramework#97]
Unless I just haven't figured out how to do this, but can we have capability to allow the end user of the tool to enter text into part of the name. Maybe limiting that text to x amount of characters.

e.g. rg-eu-prd-(custom text)-01

**Comment by BryanSoltis** [comment]
Hi @JClarke90 ,

I wanted to let you know we release "Free Form Text" components today in v2.7.0 that should allow this functionality.  Hope you like it!

https://github.com/BryanSoltis/CloudAdoptionFramework/blob/master/ready/AzNamingTool/RELEASENOTES.md

- Bryan
